# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/" # Location of package manifests
    target-branch: "future"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    groups:
      major-updates:
        update-types: ["major"]
    schedule:
      interval: "weekly"
      # Check for nuget updates on Fridays
      day: "friday"
      time: "08:00"
      timezone: "Europe/Berlin"
    # Labels on pull requests for security and version updates
    labels:
      - "nuget"
      - "dependencies"
  - package-ecosystem: "npm"
    directory: "/src/Moryx.CommandCenter.Web/"
    target-branch: "future"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    groups:
      npm-major:
        update-types: ["major"]
    schedule:
      interval: "weekly"
      day: "friday"
      time: "08:10"
      timezone: "Europe/Berlin"
    labels:
      - "npm"
      - "dependencies"
  - package-ecosystem: "npm"
    directory: "/src/Moryx.ControlSystem.ProcessEngine.Web/"
    target-branch: "future"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    groups:
      npm-major:
        update-types: ["major"]
    schedule:
      interval: "weekly"
      day: "friday"
      time: "08:15"
      timezone: "Europe/Berlin"
    labels:
      - "npm"
      - "dependencies"
  - package-ecosystem: "npm"
    directory: "/src/Moryx.VisualInstructions.Web/"
    target-branch: "future"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    groups:
      npm-major:
        update-types: ["major"]
    schedule:
      interval: "weekly"
      day: "friday"
      time: "08:20"
      timezone: "Europe/Berlin"
    labels:
      - "npm"
      - "dependencies"
  - package-ecosystem: "npm"
    directory: "/src/Moryx.FactoryMonitor.Web/"
    target-branch: "future"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    groups:
      npm-major:
        update-types: ["major"]
    schedule:
      interval: "weekly"
      day: "friday"
      time: "08:25"
      timezone: "Europe/Berlin"
    labels:
      - "npm"
      - "dependencies"
  - package-ecosystem: "npm"
    directory: "/src/Moryx.Media.Web/"
    target-branch: "future"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    groups:
      npm-major:
        update-types: ["major"]
    schedule:
      interval: "weekly"
      day: "friday"
      time: "08:30"
      timezone: "Europe/Berlin"
    labels:
      - "npm"
      - "dependencies"
  - package-ecosystem: "npm"
    directory: "/src/Moryx.Notifications.Web/"
    target-branch: "future"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    groups:
      npm-major:
        update-types: ["major"]
    schedule:
      interval: "weekly"
      day: "friday"
      time: "08:35"
      timezone: "Europe/Berlin"
    labels:
      - "npm"
      - "dependencies"
  - package-ecosystem: "npm"
    directory: "/src/Moryx.Operators.Web/"
    target-branch: "future"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    groups:
      npm-major:
        update-types: ["major"]
    schedule:
      interval: "weekly"
      day: "friday"
      time: "08:40"
      timezone: "Europe/Berlin"
    labels:
      - "npm"
      - "dependencies"
  - package-ecosystem: "npm"
    directory: "/src/Moryx.Orders.Web/"
    target-branch: "future"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    groups:
      npm-major:
        update-types: ["major"]
    schedule:
      interval: "weekly"
      day: "friday"
      time: "08:45"
      timezone: "Europe/Berlin"
    labels:
      - "npm"
      - "dependencies"
  - package-ecosystem: "npm"
    directory: "/src/Moryx.Products.Web/"
    target-branch: "future"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    groups:
      npm-major:
        update-types: ["major"]
    schedule:
      interval: "weekly"
      day: "friday"
      time: "08:50"
      timezone: "Europe/Berlin"
    labels:
      - "npm"
      - "dependencies"
  - package-ecosystem: "npm"
    directory: "/src/Moryx.Resources.Web/"
    target-branch: "future"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    groups:
      npm-major:
        update-types: ["major"]
    schedule:
      interval: "weekly"
      day: "friday"
      time: "08:55"
      timezone: "Europe/Berlin"
    labels:
      - "npm"
      - "dependencies"
  - package-ecosystem: "npm"
    directory: "/src/Moryx.Shifts.Web/"
    target-branch: "future"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    groups:
      npm-major:
        update-types: ["major"]
    schedule:
      interval: "weekly"
      day: "friday"
      time: "09:00"
      timezone: "Europe/Berlin"
    labels:
      - "npm"
      - "dependencies"
  - package-ecosystem: "npm"
    directory: "/src/Moryx.Workplans.Web/"
    target-branch: "future"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    groups:
      npm-major:
        update-types: ["major"]
    schedule:
      interval: "weekly"
      day: "friday"
      time: "09:05"
      timezone: "Europe/Berlin"
    labels:
      - "npm"
      - "dependencies"
